


    mongo:  
      image: mongo
      volumes: 
        - database:/data/db
      ports: 
        - "27017:27017"
      
    app:
      build: .
      dockerfile: Dockerfile 
      ports: 
        - "8087:8080"
      links:
        - mongo
    
    
    
    
   