# spring:

       # autoconfigure:
        #  -  exclude: org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration
#    data:
#        mongodb:
#            host: localhost
#            port: 27017
#            database: MongoDB